# Device
device: True

# Mode
mode : "service"

# Data Configuration
data:
  root: "/workspace/"
  edge_exist: False
  cloth_path: "/workspace/dataset/service_cloth/"
  edge_path: "/workspace/dataset/service_edge/"
  person_path: "/workspace/dataset/service_img/"
  output_path: "/workspace/results/"

