# Device
device: True

# Mode
mode : "service"

# Data Configuration
data:
  root: "dataset/"
  edge_exist: False
  cloth_path: "dataset/service_cloth/"
  edge_path: "dataset/service_edge/"
  person_path: "dataset/service_img/"

